x

diff --git a/.github/workflows/python_build.yml b/.github/workflows/python_build.yml
--- a/.github/workflows/python_build.yml
+++ b/.github/workflows/python_build.yml
@@ -52,15 +52,47 @@ jobs:
     - name: Create MCP shell script
       run: |
         # ---
-          cat >"${LIB_MCP}" <<END
+          cat > ${LIB_MCP} <<EOF
         set +e
         declare -i rc=0
         declare resp=""
-        END
+
+        function CheckRC()
+        {
+          if (( rc )); then
+            op_failed
+            printf "\nAn error has occurred!\n\n"
+            printf "Code %s\n%s\n" \$rc "\$resp"
+            exit 1
+          fi
+        # ---
+          op_ok
+        }
+
+        function msg_info()
+        {
+          printf "%s... " "\$1"
+        }
+
+        function ApplyPatch()
+        {
+          for _patch in "\$@"; do
+            echo "Applying \$_patch"
+            patch -Np1 -i "\${G_WORKSPACE}/\$_patch"
+          done
+        }
+
+        function op_ok()     { _op_status "ok"     "\${@}"; }
+        function op_failed() { _op_status "failed" "\${@}"; }
+
+        function _op_status()
+        {
+            printf "%s\n" "\$1"
+        }
+        EOF
 
   build_win32:
     name: 'Windows (x86)'
-    if: ${{ false }}
     runs-on: windows-latest
     needs: initialize
     steps:
